'use client';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { CssVarsProvider, StyledEngineProvider } from '@mui/joy/styles';
import { theme } from '@/component/theme/colors';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledEngineProvider injectFirst>
          <CssVarsProvider defaultMode="system" theme={theme}>
            {children}
          </CssVarsProvider>
        </StyledEngineProvider>
      </body>
    </html>
  );
}
