'use client';
import { MainLayout } from '@/components/layout/main-layout';
import { redirect } from 'next/navigation';
import { useEffect } from 'react';

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  useEffect(() => {
    const auth = localStorage.getItem('user');
    if (!auth) {
      return redirect('/login');
    }
  }, []);
  return (
    <html lang="en">
      <body>
        <MainLayout children={children} />
      </body>
    </html>
  );
}
